### ISSUE TITLE
Proposal to Implement Code Formatting Standards for Contributor Consistency

### ISSUE THREAD

**Issue by josemanuel22** [JuliaEarth/ExtremeStats.jl#32]
I haven't found a `.JuliaFormatter.toml` or a `FormatCheck.yml`. I think it's important to have these if other users are going to contribute to the package. I can add them myself. Which style is preferred: [SciMLStyle](https://github.com/SciML/SciMLStyle), [BlueStyle](https://github.com/JuliaDiff/BlueStyle), [YasStyle](https://github.com/jrevels/YASGuide)?

**Comment by juliohm** [comment]
We have a `.JuliaFormatter.toml` for the org. Appreciate if you can copy it from here: https://github.com/JuliaEarth/GeoStatsBase.jl

**Comment by juliohm** [comment]
Fixed on master.
